// Inject the product gallery into the flattened casestudies.html.
//
// The page ships from the live site with the "Selected Work" area holding four
// debossed client logos. This swaps that block for the gallery container
// (filter host + tile markers) and wires the gallery stylesheet and script,
// using a real HTML parser so the surrounding Salient markup is untouched.
//
// Idempotent: if the container is already present it only re-verifies the
// asset links. Run scripts/build-gallery-html.mjs afterwards to fill tiles.
//
// Run: node scripts/inject-gallery.mjs

import { readFile, writeFile } from 'node:fs/promises';
import * as cheerio from 'cheerio';

const PAGE = 'casestudies.html';

const CONTAINER =
  '<div id="bc-gallery">\n' +
  '  <div id="gallery-filters"></div>\n' +
  '  <!-- BEGIN gallery-tiles : generated by scripts/build-gallery-html.mjs -->\n' +
  '  <!-- END gallery-tiles -->\n' +
  '</div>';

const html = await readFile(PAGE, 'utf8');
const $ = cheerio.load(html, { decodeEntities: false });

// Find the smallest ancestor holding all four debossed logos.
const logos = $('img[src*="PLAIN-DEBOSS"]');
if (logos.length < 4 && $('#bc-gallery').length === 0) {
  console.error(`FAIL: expected 4 logo images, found ${logos.length}, and no existing #bc-gallery`);
  process.exit(1);
}

let injected = false;

if ($('#bc-gallery').length === 0) {
  let wrap = logos.first();
  for (let i = 0; i < 12; i++) {
    const p = wrap.parent();
    if (!p.length) break;
    wrap = p;
    if (wrap.find('img[src*="PLAIN-DEBOSS"]').length === logos.length) break;
  }
  wrap.empty().append(CONTAINER);
  injected = true;
}

// Wire the stylesheet in <head> and the script before </body>, once each.
if ($('link[href="css/gallery.css"]').length === 0) {
  $('head').append('\n<link rel="stylesheet" href="css/gallery.css">\n');
}
if ($('script[src="js/gallery.js"]').length === 0) {
  $('body').append('\n<script src="js/gallery.js" defer></script>\n');
}

await writeFile(PAGE, $.html(), 'utf8');

console.log(injected ? 'container injected' : 'container already present');
console.log('stylesheet linked:', $('link[href="css/gallery.css"]').length > 0);
console.log('script linked:', $('script[src="js/gallery.js"]').length > 0);
console.log('RESULT=PASS');
